title = "Convention"
author = "Sentenz"
description = "General articles, conventions and guides for software development."
language = "en"
theme = "default"

[book]
multilingual = false

[output]
format = "html"
html = { theme = "default" }
