baseURL = "https://sentenz.github.io/convention/"
languageCode = "en-us"
title = "Convention"
publishDir = "public"

[permalinks]
    articles = "/:year/:month/:day/:title/"
    convention = "/:year/:month/:day/:title/"
    guides = "/:year/:month/:day/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    mainSections = ["articles", "convention", "guides"]

[[module]]
  [[module.mounts]]
    source = "internal"
    target = "content"
