# SPDX-License-Identifier: Apache-2.0

site_name: Convention
site_description: Software development conventions, guides and articles.
repo_name: sentenz/convention
repo_url: https://github.com/sentenz/convention

docs_dir: content
site_dir: public
exclude_docs: |
  decisions/draft/

hooks:
  - content/assets/hooks/mkdocs_hooks.py

extra_css:
  - assets/css/style.css

plugins:
  - search
  - awesome-nav

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  features:
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
