---
trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-22.04
resources:
  repositories:
    - repository: self
      persistCredentials: true
stages:
  - stage: continuous_release
    jobs:
      - job: continuous_release
        displayName: Continuous Release
        timeoutInMinutes: 5
        steps:
          - task: Bash@3
            displayName: Setup Release
            inputs:
              targetType: inline
              script: |
                make setup-continuous-release
          - task: Bash@3
            displayName: Run Release
            env:
              GIT_CREDENTIALS: $(System.AccessToken)
            inputs:
              targetType: inline
              script: |
                make run-continuous-release
