---
trigger: none
pool:
  vmImage: ubuntu-22.04
resources:
  pipelines:
    - pipeline: Continuous Integration
      source: continuous-integration
      trigger:
        enabled: true
stages:
  - stage: continuous_testing
    jobs:
      - job: continuous_testing
        displayName: Continuous Testing
        timeoutInMinutes: 20
        steps:
          - task: Bash@3
            displayName: Setup Testing
            inputs:
              targetType: inline
              script: |
                make setup-continuous-testing
          - task: Bash@3
            displayName: Run Testing
            continueOnError: true
            inputs:
              targetType: inline
              script: |
                make run-continuous-testing
          - task: CopyFiles@2
            displayName: Upload Artifacts
            inputs:
              contents: "logs/**"
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            displayName: Publish Artifacts
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: continuous-testing-artifact
