#!/bin/bash
#
# The "pre-commit" hook is run just before "commit" starts doing its job, and can prevent the
# command from running by exiting with non-zero status.
#
# Details:
# Perform to verify the codebase is about to be committed.
#
# Arguments:
#   None
#
# Returns:
#   Exitcode

# -x: print a trace (debug)
# -u: treat unset variables
# -o pipefail: return value of a pipeline
set -uo pipefail

# Include Scripts

source ./scripts/shell/log.sh
source ./scripts/shell/fs.sh
source ./scripts/shell/git.sh
source ./scripts/shell/hook.sh

# Constant Variables

LOG_FILE="$(git_get_root_dir)/logs/githooks/pre-commit.log"
readonly LOG_FILE

# Internal Functions

run_pre_commit() {
  local -i result=0

  fs_create_file "${LOG_FILE}"

  hook_enforce_coding_standards "make run-linter-staged" &>"${LOG_FILE}"
  ((result = $?))
  if ((result == 1)); then
    log_message "githooks" "pre-push" "${result}"

    return "${result}"
  fi

  fs_remove_file "${LOG_FILE}"

  return "${result}"
}

# Control Flow Logic

run_pre_commit
exit "${?}"
