---
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ci-release-codebase

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  release:
    if: ${{ always() }}
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm

      - name: Install NPM
        run: |
          npm ci --ignore-scripts

      - name: Release Codebase
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
