---
name: Continuous-Security
on:
  pull_request:
    branches:
      - main
jobs:
  security:
    if: ${{ github.event_name == 'pull_request' }}
    name: continuous-security
    runs-on: ubuntu-22.04
    steps:
      - name: Verify Contributor
        run: |
          echo ${{ github.event.pull_request.user.login }}
