# SPDX-License-Identifier: Apache-2.0
---
name: Conventional Commits
on: [pull_request]
jobs:
  conventional-commits:
    name: conventional-commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
