# SPDX-License-Identifier: Apache-2.0
---
name: SSG
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-rust@v1
        with:
          toolchain: stable
      - name: Install mdBook
        run: cargo install mdbook
      - name: Build the book
        run: mdbook build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
