# SPDX-License-Identifier: Apache-2.0

name: TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  trufflehog:
    name: TruffleHog Action
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog
        uses: sentenz/actions/trufflehog@c600775dda21753455e72c46d37d32b452c35817 # 1.5.0
        with:
          path: ./
          extra-args: --debug
